export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_COMPLETE = 'FETCH_CONTACTS_COMPLETE';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CREATE_CONTACT_COMPLETE = 'CREATE_CONTACTS_COMPLETE';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACTS_ERROR';

export const START_CREATION = 'START_CREATION';
export const STOP_CREATION = 'STOP_CREATION';

export const UPDATE_CONTACT = 'UPDATE_CONTACTS';
export const UPDATE_CONTACT_COMPLETE = 'UPDATE_CONTACTS_COMPLETE';
export const UPDATE_CONTACT_ERROR = 'UPDATE_CONTACTS_ERROR';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_COMPLETE = 'DELETE_CONTACT_COMPLETE';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const SELECT_CONTACT = 'SELECT_CONTACT';
export const SELECT_CONTACT_COMPLETE = 'SELECT_CONTACT_COMPLETE';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';

export const EDIT_CONTACT = 'EDIT_CONTACT';
export const CLEAR_EDITING = 'CLEAR_EDITING';

export const NAVIGATE = 'NAVIGATE';
